on:
    workflow_call:
        inputs:
            deploy:
                type: boolean
                description: "If true, the documentation will be deployed."
                default: false

jobs:
    run-docs:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Build docs
          run: mkdocs build --verbose --clean
        - name: Build and push docs
          if: inputs.deploy
          run: mkdocs gh-deploy --force